### ISSUE TITLE
Writing more than 1020 characters from the LabVIEW library results in a crash

### ISSUE THREAD

**Issue by chinghwayu** [JamesMc86/LabVIEW-CLI#6]
I'm guessing that there's a 1024 character limit somewhere that's causing a crash. OUTP + 1020 = 1024.

![labview-cli crash](https://cloud.githubusercontent.com/assets/11654708/17530019/8e33d264-5e2a-11e6-9b09-1dc9e7b22868.png)

**Comment by rose-a** [comment]
Experienced that too...

In my case this happens when a LabVIEW build which was triggered via CI using LabVIEW-CLI fails and then tries to output the Error via CLI...

**Comment by JamesMc86** [comment]
Will aim to get to this today - will increase the buffer to say 8k and then get the LabVIEW client to break up any messages longer than this

**Comment by JamesMc86** [comment]
This should be fixed in v1.2.0 which I have just put up in the releases section. Please give it a go and let me know if there are problems.

I've rolled in both of your other changes as well, thanks for getting involved!

**Comment by chinghwayu** [comment]
It's still crashing but now, the max number of characters that can be sent before crash is now 2997. Haven't looked at code but developers are reporting this.
